app1/config/routes.rb
Rails.application.routes.draw do
  
  get 'orders/index'

  devise_for :users
  get 'cart_line_items/index'

  get 'cart_line_items/create'

  get 'sites/index'

  resources :orders
  resources :cart_line_items
  resources :products
  resources :categories

   root 'categories#index'
  resources :sites 
   

end

app1/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app1/app/controllers/cart_line_items_controller.rb
class CartLineItemsController < ApplicationController
  def index
  	response = HTTParty.get("http://localhost:3003/api/v1/line_items/#{current_user.id}")
  	@cart_line_items = JSON.parse(response.body)
  end
  def destroy
  	@line_id=params[:id]
  	HTTParty.get("http://localhost:3003/api/v1/line_items?line_id=#{@line_id}")
  	redirect_to "http://localhost:3000/cart_line_items"
  	
  end
end

app1/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	response = HTTParty.get("http://localhost:3001/api/v1/categories.json")
  	@categories = JSON.parse(response.body)

  end

  def show
  	#binding.pry
  	response = HTTParty.get("http://localhost:3001/api/v1/categories/#{params["id"]}")
  	@category = JSON.parse(response.body)
  	response_product = HTTParty.get("http://localhost:3002/api/v1/products")
    @products = JSON.parse(response_product.body)
  end
end

app1/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  	response = HTTParty.get("http://localhost:3004/api/v1/orders/#{current_user.id}")
  	@orders = JSON.parse(response.body)
  end
end

app1/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	response = HTTParty.get("http://localhost:3002/api/v1/products")
    @products = JSON.parse(response.body)
  end

  def show
  	response = HTTParty.get("http://localhost:3002/api/v1/products/#{params["id"]}")
    @product = JSON.parse(response.body)
  end
end

app1/app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
  	response = HTTParty.get("http://localhost:3001/api/v1/categories.json")
  	@categories = JSON.parse(response.body)

  	response = HTTParty.get("http://localhost:3002/api/v1/products")

  	@products = JSON.parse(response.body)
  end

  def show
  	response_category = HTTParty.get("http://localhost:3001/api/v1/categories/#{params["id"]}")
  	@category = JSON.parse(response_category.body)
    response_product = HTTParty.get("http://localhost:3002/api/v1/products")
    @products = JSON.parse(response_product.body)
  end
  
  def show_product
    binding.pry
    response = HTTParty.get("http://localhost:3002/api/v1/products/#{params["id"]}")
    @product = JSON.parse(response.body)

  end
end

app1/app/helpers/application_helper.rb
module ApplicationHelper
end

app1/app/helpers/cart_line_items_helper.rb
module CartLineItemsHelper
end

app1/app/helpers/categories_helper.rb
module CategoriesHelper
end

app1/app/helpers/orders_helper.rb
module OrdersHelper
end

app1/app/helpers/products_helper.rb
module ProductsHelper
end

app1/app/helpers/sites_helper.rb
module SitesHelper
end

app1/app/views/cart_line_items/index.html.erb
<h1>CartLineItems#index</h1>

<%total=0%>
<table border="1">
<thead>
	<tr>
		<th>Name</th>
		<th>Quantity</th>
		<th>Price</th>
		<th>Action</th>
	</tr>
</thead>
<tbody>
	
	<%@cart_line_items.each do |item|%>
	<tr>
		<%response = HTTParty.get("http://localhost:3002/api/v1/products/#{item["product_id"]}")%>
		<%product = JSON.parse(response.body)%>
 	   <td><%=product["name"]%></td>
	    <td>	    	
	    	<%= form_tag("http://localhost:3003/api/v1/line_items",method: :patch) do %>
	    	<%= select_tag :quantity, options_for_select(1..10,item["quantity"])%>
	    	<%= submit_tag "Update"%>
	    	<%end%>
	    </td>
	    <td><%=product["price"]%></td>
	    <%total += item["quantity"] * product["price"]%>
	    <td><%=link_to "Remove", cart_line_item_path(item["id"]),method: :delete%></td>
	</tr>
	<%end%>
<%#HTTParty.delete("http://localhost:3003/api/v1/line_items/#{self.user_id}")%>	
</tbody>
</table>
<%=total%>
<%=form_tag("http://localhost:3004/api/v1/orders", method: :post) do%>
	<%=hidden_field_tag :user_id, current_user.id%>
	<%=hidden_field_tag :total, total %>
	<%=submit_tag "checkout"%>
<%end%>

app1/app/views/categories/index.html.erb
<h1>category list</h1>
<ul>
<%@categories.each do |category|%>
	<li><%=link_to category["name"],category_path(category["id"])%></li>
<%end%>

</ul>

app1/app/views/categories/show.html.erb
<h2>Category</h2>

Name:<%=@category["name"]%>
<br><br>
<strong>Product Listing</strong><br>
<ul>
		<%@products.each do |product|%>
			<%if @category["id"] == product["category_id"]%>
				<li><%=link_to product["name"],product_path(product["id"])%></li>
			<%end%>
		<%end%>
	</ul>

app1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%if user_signed_in?%>
	<%=current_user.email%> |
	<%=link_to "logout", destroy_user_session_path, method: :delete%> |
	<%=link_to "Categories", categories_path%> |
	<%=link_to "Products",products_path%> |
	<%=link_to "Cart",cart_line_items_path%> |
	<%=link_to "Orders", orders_path%> 
<%else%>

	<%=link_to "login",new_user_session_path%> |
	<%=link_to "Register",new_user_registration_path%> |
	<%=link_to "Categories", categories_path%> |
	<%=link_to "Products"%>
<%end%>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app1/app/views/orders/index.html.erb
<h1>Orders Details</h1>

<%count=0%>
<table border="1">
	<thead>
		<tr>
			<th>No.</th>
			<th>Order number</th>
			<th>Order date</th>
			<th>Total</th>
		</tr>
	</thead>
	<tbody>
		<%@orders.each do |order|%>
		<tr>
			<td><%=count += 1%></td>
			<td><%=order["order_no"]%></td>
			<td><%=order["order_date"]%></td>
			<td><%=order["total"]%></td>
		</tr>
		<%end%>
	</tbody>
</table>

app1/app/views/products/index.html.erb
<h2>Product list</h2>


<ul>
	<%@products.each do |product|%>
	<li><%=link_to product["name"],product_path(product["id"])%></li>
	<%end%>
</ul>

app1/app/views/products/show.html.erb
<h2>Product Details</h2>
Name:<%=@product["name"]%><br>
Price:<%=@product["price"]%><br>


<%= form_tag("http://localhost:3003/api/v1/line_items",method: :post) do %>
	
	<label>Quantity</label>
	<%= select_tag :quantity, options_for_select(1..10,1)%><br>
	<%= hidden_field_tag :product_id , @product["id"]%>
	<%= hidden_field_tag :user_id , current_user.id%>
	<%=submit_tag "Add to cart"%>
<%end%>

app1/app/views/sites/index.html.erb
<h1>category list</h1>
<ul>
<%@categories.each do |category|%>
	<li><%=link_to category["name"],category_path(category["id"])%></li>
<%end%>

</ul>



<h1>Product list</h1>
<ul>
<%@products.each do |product|%>
	<li><%=product["name"]%>-<%=product["price"]%></li>
<%end%>

</ul>

app1/app/views/sites/show.html.erb
<h2>Category</h2>

Name:<%=@category["name"]%>
<br><br>
<strong>Product Listing</strong><br>

<%if @products.is_a?(Hash)%>
	<p>No products are available for this category</p>
<%else%>
	<ul>
		<%@products.each do |product|%>
			<%if @category["id"] == product["category_id"]%>
				<li><%=link_to product["name"],site_show_product_path(product["id"])%></li>
			<%end%>
		<%end%>
	</ul>
<%end%>

app1/app/views/sites/show_product.html.erb
<h2>Product Details</h2>
Name:<%=@product%>